### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Nyaacinth** [HuajiMUR233/MoreAPIs#1]
首先感谢您开发了这样一个 API 插件，这个插件*看起来*可以解决不少在 MCDReforged 1.x 中的痛点问题呢

但是咱在尝试过程中发现了一些问题

- 死亡信息字典相关

不在源码仓库内：想 PR 而不能的痛（
缺失部分条目：目前死亡信息字典缺失部分无附加信息的条目，如 "\<player> fell out of the world"

- 事件 death_message 的监听器传递参数为 i 

即匹配到本条死亡信息的原始正则表达式，也许这里可以直接传递角色名称或 info ？

- 奇怪的文件结构

仓库内放置了 MoreAPIs 模块文件夹和 MoreAPIs.py ，但实际在 mcdr 运行时 MoreAPIs 文件夹是无法作为模块加载的，会导致插件出错无法运行：

'MoreAPIs' is not a package

```
[MCDR] [03:12:47] [TaskExecutor/ERROR]: Fail to load plugin RegularPlugin[file=MoreAPIs.py,path=plugins/MoreAPIs.py,state=0]
Traceback (most recent call last):
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/plugin_manager.py", line 170, in __load_plugin
    plugin.load()
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/regular_plugin.py", line 87, in load
    self.__load_instance()
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/regular_plugin.py", line 67, in __load_instance
    self.module_instance = misc_util.load_source(self.file_path)
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/utils/misc_util.py", line 31, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/plugins/MoreAPIs.py", line 31, in <module>
    from MoreAPIs.StatusPing import StatusPing
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/MoreAPIs.py", line 31, in <module>
    from MoreAPIs.StatusPing import StatusPing
ModuleNotFoundError: No module named 'MoreAPIs.StatusPing'; 'MoreAPIs' is not a package
```

**Comment by HuajiMUR233** [comment]
首先，感谢你的使用
这个插件在编写过程中没有过多的进行测试，这确实是我的问题
然后就是今晚修(

**Comment by Nyaacinth** [comment]
多谢了！
看起来在咱的使用场景下大部分都没有问题了，不过在查看 death_message 部分的时候发现事件触发时传递的参数似乎仍为匹配到本条信息的原始正则表达式。可能这个传递的参数不太易于使用呢。如果传递的是 info.content 也许会好很多？

原始块：
```
for i in _death_messages["msgs"]:
    if re.fullmatch(i, info.content):
        server.dispatch_event(_events["death_message"], (i,))
        break
```

**Comment by HuajiMUR233** [comment]
it's a bug 😢

**Comment by HuajiMUR233** [comment]
\fixed/

**Comment by Nyaacinth** [comment]
好耶！

**Comment by HuajiMUR233** [comment]
\好耶/

**Comment by Nyaacinth** [comment]
抱歉还是需要 Reopen 一下，似乎 MoreAPIs 在 mcdr 中直接运行仍然无法正常加载呢

目录结构或者其他方面是否需要有特殊的设置呢

目录结构 ->
- plugins
  - More_APIs
  - MinecraftDataAPI.py
  - MoreAPIs.py
  - Telekinesis.py

Traceback ->
```
[MCDR] [23:58:12] [TaskExecutor/ERROR]: Fail to load plugin RegularPlugin[file=MoreAPIs.py,path=plugins/MoreAPIs.py,state=0]
Traceback (most recent call last):
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/plugin_manager.py", line 170, in __load_plugin
    plugin.load()
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/regular_plugin.py", line 87, in load
    self.__load_instance()
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/plugin/regular_plugin.py", line 67, in __load_instance
    self.module_instance = misc_util.load_source(self.file_path)
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/lib/python3.9/site-packages/mcdreforged/utils/misc_util.py", line 31, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hiasinsu/文档/MCDR/Telekinesis_TestEnv/plugins/MoreAPIs.py", line 32, in <module>
    from .More_APIs.StatusPing import StatusPing
ImportError: attempted relative import with no known parent package
```

**Comment by HuajiMUR233** [comment]
e

**Comment by HuajiMUR233** [comment]
哦刚刚手抖close了，刚刚试着修了下，你试试吧

**Comment by Nyaacinth** [comment]
抱歉之前在忙别的，回复晚了
我测试确实是没有问题了，但发现 death_messages.yml 内装的死亡信息有极大问题。几乎完全匹配不到玩家死亡
按照 wiki 重写了一份，之后会提交 PR，麻烦您了

**Comment by Nyaacinth** [comment]
（疑惑.jpg
仔细核对 wiki 后发现似乎之前的 death_messages.yml 是对应 13w02a ~ 13w04a (1.5) 时期的死亡信息生成系统的...

**Comment by Nyaacinth** [comment]
https://github.com/HuajiMUR233/MoreAPIs/pull/2

**Comment by HuajiMUR233** [comment]
额，我是从英文wiki下面的那个集合那里复制的，可能是那个的问题?

**Comment by Nyaacinth** [comment]
这个就不太清楚了呢...

现在相关的问题看起来已经完整解决了， Issue 先关了（
