### ISSUE TITLE
萌新不懂就问

### ISSUE THREAD

**Issue by Zachary-p** [HuajiMUR233/MoreAPIs#3]
问一下这个怎么搞
Exception in thread More APIs:
Exception in thread More APIs:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    self.run()
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 100, in on_info
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 100, in on_info
    for i in _death_messages["msgs"]:
KeyError: 'msgs'
    for i in _death_messages["msgs"]:
KeyError: 'msgs'

**Comment by HuajiMUR233** [comment]
应该是我的问题?
提供下MCDR版本与系统版本可否

**Comment by HuajiMUR233** [comment]
刚刚重新看了下自己代码，待会修掉

**Comment by Zachary-p** [comment]
用的mcdr 1.5+centos7.9
谢啦

Huaji_MUR233 ***@***.***> 于2021年6月24日周四 上午11:16写道：

**Comment by HuajiMUR233** [comment]
****，为什么github会自己关掉issue
尝试修复了下，你可以去试试还有没有这个问题(

**Comment by Zachary-p** [comment]
变成这样了淦

Exception in thread More APIs:
Exception in thread More APIs:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
    self.run()
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 58, in on_info
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 58, in on_info
    death_message = __get_death_messages(server)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 173, in __get_death_messages
    death_message = __get_death_messages(server)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 173, in __get_death_messages
    with open(
NotADirectoryError: [Errno 20] Not a directory: 'plugins/MoreAPIs.py/../More_APIs/death_messages.yml'
    with open(
NotADirectoryError: [Errno 20] Not a directory: 'plugins/MoreAPIs.py/../More_APIs/death_messages.yml'
[Server] [22:07:18] [Server thread/INFO]: There are 2 of a max of 114514 players online: 
Exception in thread More APIs:
Traceback (most recent call last):
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 58, in on_info
    death_message = __get_death_messages(server)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 173, in __get_death_messages
    with open(
NotADirectoryError: [Errno 20] Not a directory: 'plugins/MoreAPIs.py/../More_APIs/death_messages.yml'

**Comment by HuajiMUR233** [comment]
我是sb

**Comment by Zachary-p** [comment]
不至于不至于

**Comment by HuajiMUR233** [comment]
用脚修了下，试试？

**Comment by Zachary-p** [comment]
好耶
可以了！

**Comment by HuajiMUR233** [comment]
没问题了的话这个issue我就先close了
