### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Zachary-p** [HuajiMUR233/MoreAPIs#4]
草草草
自动备份之后有的这个

Traceback (most recent call last):
  File "/opt/python395/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/python395/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 87, in on_info
    server.dispatch_event(_events["saved_game"])
  File "/run/media/root/SSD/MCDR/mcdreforged/plugin/server_interface.py", line 38, in wrap
    return func(self, *args, **kwargs)
TypeError: dispatch_event() missing 1 required positional argument: 'args'

**Comment by HuajiMUR233** [comment]
试试?

**Comment by Zachary-p** [comment]
可以用 但是控制台看着好难受啊淦

**Comment by Zachary-p** [comment]
ok了
