### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Zachary-p** [HuajiMUR233/MoreAPIs#5]
我又来辣!(雾

莫名其妙就变成这样了

[MCDR] [19:59:58] [TaskExecutor/ERROR]: 插件 RegularPlugin[file=MoreAPIs.py,path=plugins/MoreAPIs.py,state=0] 加载失败
Traceback (most recent call last):
  File "/run/media/root/SSD/MCDR/mcdreforged/plugin/plugin_manager.py", line 167, in __load_plugin
    plugin.load()
  File "/run/media/root/SSD/MCDR/mcdreforged/plugin/regular_plugin.py", line 87, in load
    self.__load_instance()
  File "/run/media/root/SSD/MCDR/mcdreforged/plugin/regular_plugin.py", line 67, in __load_instance
    self.module_instance = misc_util.load_source(self.file_path)
  File "/run/media/root/SSD/MCDR/mcdreforged/utils/misc_util.py", line 31, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 851, in exec_module
  File "<frozen importlib._bootstrap_external>", line 988, in get_code
  File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/run/media/root/SSD/MCDR/plugins/MoreAPIs.py", line 87
    server.dispatch_event(_events["saved_game"],(,))
                                                 ^
SyntaxError: invalid syntax

**Comment by Zachary-p** [comment]
刚备份过服务端

**Comment by HuajiMUR233** [comment]
✌刚刚完全没修好

**Comment by HuajiMUR233** [comment]
我水个时间上去吧

**Comment by HuajiMUR233** [comment]
可能修掉了，你试试

**Comment by Zachary-p** [comment]
我试试

**Comment by Zachary-p** [comment]
\修好了好耶/

**Comment by HuajiMUR233** [comment]
好耶
